### ISSUE TITLE
Speed-up computation by using pow(x,y,z) function

### ISSUE THREAD

**Issue by chris3k** [plizonczyk/noiseprotocol#1]
https://github.com/plizonczyk/noiseprotocol/blob/ed4a452cc50da776c94940570c6b068cf64106a8/noise/crypto.py#L64

> pow(x, y[, z])
> Return x to the power y; if z is present, return x to the power y, modulo z (computed more efficiently than pow(x, y) % z). The two-argument form pow(x, y) is equivalent to using the power operator: x**y.

**Comment by plizonczyk** [comment]
I've somehow missed it while doing this change in the return statement. Thanks!

**Comment by aafanasyev** [comment]
Not sure if the pow() is the fastest solution. An observation based on:
https://stackoverflow.com/questions/20969773/exponentials-in-python-x-y-vs-math-powx-y 
http://www.talking5.info/python-xy-vs-powxy/

**Comment by chris3k** [comment]
@aafanasyev it depends on x, y and z values.
```
>>> timeit.timeit("pow(2, (43139347248+43139347036), 3139348633)", number=10000000)
10.762556076049805
>>> timeit.timeit("(2 ** (43139347248+43139347036)) % 3139348633", number=10000000)
forever... :)
```
