### ISSUE TITLE
Feature request: Support for Noise_XK_secp256k1_ChaChaPoly_SHA256

### ISSUE THREAD

**Issue by practicalswift** [plizonczyk/noiseprotocol#18]
Having `noiseprotocol` support `Noise_XK_secp256k1_ChaChaPoly_SHA256` (the Lightning variant of Noise) would be very useful for developers looking to build Lightning Network related projects in Python.

See [BOLT #8: Encrypted and Authenticated Transport](https://github.com/lightningnetwork/lightning-rfc/blob/master/08-transport.md#noise-protocol-instantiation) for details.

As far as I know there are no Noise protocol frameworks in Python with support for `Noise_XK_secp256k1_ChaChaPoly_SHA256`.

**Comment by plizonczyk** [comment]
Scheduled for 0.3 release :)

**Comment by practicalswift** [comment]
@plizonczyk Very glad to hear that! Is the `Noise_XK_secp256k1_ChaChaPoly_SHA256` development taking place in a specific branch/fork or is that job yet to be started? :-)

**Comment by plizonczyk** [comment]
@practicalswift Took a while... 😞 noiseprotocol v 0.3.0 is now released and supports non-default backends.
