### ISSUE TITLE
Prefer tuples over lists in constant data types

### ISSUE THREAD

**Issue by chris3k** [plizonczyk/noiseprotocol#2]
https://github.com/plizonczyk/noiseprotocol/blob/ed4a452cc50da776c94940570c6b068cf64106a8/noise/patterns.py#L63

**Comment by plizonczyk** [comment]
Good point - tuples are 1) faster 2) immutable. Will be changed throughout the project. Thanks!

**Comment by chris3k** [comment]
and 3) uses less memory :)
