### ISSUE TITLE
why pin cryptography==2.1.4?

### ISSUE THREAD

**Issue by warner** [plizonczyk/noiseprotocol#20]
I can appreciate requiring a specific version *or newer*, e.g. `cryptography>=2.1.4`, but why prevent more recent versions from being used? The pin causes my project to downgrade `cryptography` when I add `noiseprotocol`, because the current release still has a pin on 2.1.3 . Making a new `noiseprotocol` release will help, but it'll probably run into the same problem again in a month or two when they make a new `cryptography` release.

Would you accept a PR to make that `>=` ?

thanks!

**Comment by warner** [comment]
Oh, I should mention it also prevents use in any project that uses e.g. `pyopenssl`, because that requires 2.1.4 or newer, and pip can't satisfy both `cryptography>=2.1.4` and `cryptography==2.1.3` at the same time.

**Comment by plizonczyk** [comment]
I'll need to review my usage of Cryptography, but I suppose that crypto primitives that are in use won't be removed. Hence - I'll probably agree to that.

**Comment by plizonczyk** [comment]
Version 0.2.2 containing your changes is live in PyPI. Thanks for your contributions!
