### ISSUE TITLE
Remove custom curve448 implementation

### ISSUE THREAD

**Issue by plizonczyk** [plizonczyk/noiseprotocol#25]
Apparently OpenSSL finally supports x448/ed448 - https://github.com/openssl/openssl/blob/master/CHANGES#L47
Will require upgrading cryptography requirement to 2.2.x as that's where's OpenSSL 1.1.1 included.

**Comment by plizonczyk** [comment]
Might be worth (or needed) to wait until this is done: https://github.com/pyca/cryptography/issues/4136

**Comment by maqp** [comment]
Just to let you know, you can already start playing with the cryptography's X448 implementation: https://github.com/reaperhulk/cryptography/tree/x448-support (:

Also, thank you very much for the work on pure-Python X448, it's been most helpful over the past few months!

**Comment by plizonczyk** [comment]
Thanks for heads up!

**Comment by plizonczyk** [comment]
FYI - as I'm removing the implementation from this repo (changes are in trunk), I've moved it to separate package - https://github.com/plizonczyk/x448-python
