### ISSUE TITLE
why no tar.gz/source distributable for 0.3.1 ?

### ISSUE THREAD

**Issue by SomberNight** [plizonczyk/noiseprotocol#42]
Previous releases, such as 0.3.0 had both a wheel and a tar.gz/zip source distributable.
0.3.1 only has a wheel uploaded to PyPI.

Compare:
https://pypi.org/project/noiseprotocol/0.3.0/#files
https://pypi.org/project/noiseprotocol/0.3.1/#files

This breaks `pip install --no-binary :all: noiseprotocol`
(or indeed pip installing anything that pulls in `noiseprotocol` as a dependency)

**Comment by plizonczyk** [comment]
Hi @SomberNight - thanks for pointing that out, I've uploaded the source dist.
