### ISSUE TITLE
Naming improvements

### ISSUE THREAD

**Issue by plizonczyk** [plizonczyk/noiseprotocol#5]
As suggested by Trevor (@trevp), NoiseBuilder name is a bit off, as it's the main interface of the library. 
Additionally, ed25519 and ed448 shall be renamed to x25519 and x448 respectively.
Filenames could be a little bit more explicit on their contents (e.g. "functions.py", "crypto.py" and "state.py")

**Comment by trevp** [comment]
Instead of NoiseBuilder, maybe NoiseConnection or NoiseSession?

The filenames seem less important, since they're not really part of the API.
